# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interf1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QMessageBox, QMenu, QSystemTrayIcon
import os
import winsound
import clipboard
import json
import requests


def copialink():
    clipboard.copy('https://www.instagram.com/maidakasaka/')
    winsound.PlaySound('SystemExclamation', winsound.SND_ALIAS | winsound.SND_ASYNC)
    QMessageBox.about(configwindow, "Grande Sucesso!!", "O link da página foi copiado para a área de transferencia!")


def sugeremudanca():
    winsound.PlaySound('SystemExclamation', winsound.SND_ALIAS | winsound.SND_ASYNC)
    QMessageBox.about(configwindow, "Sugerir Mudanças", "Por favor envie sua sugestão para: \n\n"
                                                        "Email:           sr.thales500@gmail.com\n"
                                                        "Discord:       ! Ootsuka#7559\n"
                                                        "Instagram:  @taresu_official")


def abreaoiniciar():
    winsound.PlaySound('SystemExclamation', winsound.SND_ALIAS | winsound.SND_ASYNC)
    QMessageBox.about(configwindow, "Como abrir ao iniciar?", "Mestre, para que eu possa iniciar quando o computador for ligado,"
                                                              " por favor, coloque um atalho do aplicatico na pasta Startup do windows!")


def adicionarprogramas():
    winsound.PlaySound('SystemExclamation', winsound.SND_ALIAS | winsound.SND_ASYNC)
    QMessageBox.about(configwindow, "Como adicionar programas?", "Mestre, para abrir programas pelo comando é necessario colar um atalho do programa desejado "
                                                                 "na pasta ``system32`` do windows.\n"
                                                                 "Caminho: ``C:/Windows/system32``.\n"
                                                                 "\nLembre-se de renomear o nome do atalho para o nome desejado!")


def escondeprincipal():
    MainWindow.hide()


def mostraconfigs():
    MainWindow.hide()
    configwindow.show()


def mostraprincipal():
    configwindow.close()
    MainWindow.show()


def acaosair():
    sys.exit()


class Ui_MainWindow(object):

    def setupUi(self, mainwindow):
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(800, 600)
        mainwindow.setMinimumSize(QtCore.QSize(800, 600))
        mainwindow.setMaximumSize(QtCore.QSize(800, 600))
        mainwindow.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")

        self.botaosair = QtWidgets.QToolButton(self.centralwidget)
        self.botaosair.setGeometry(QtCore.QRect(20, 540, 200, 40))

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botaosair.sizePolicy().hasHeightForWidth())

        self.botaosair.setSizePolicy(sizePolicy)
        self.botaosair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaosair.setFocusPolicy(QtCore.Qt.TabFocus)
        self.botaosair.setStyleSheet("font: bold 15px \"MS Shell Dlg 2\";\n"
                                     "background-color: rgb(252, 254, 235);\n"
                                     "border-style: outset;\n"
                                     "border-width: 2px;\n"
                                     "border-radius: 10px;\n"
                                     "border-color: red;")
        self.botaosair.setObjectName("botaosair")
        self.botaosair.clicked.connect(escondeprincipal)

        self.caixa_texto = QtWidgets.QLineEdit(self.centralwidget)
        self.caixa_texto.setGeometry(QtCore.QRect(445, 490, 345, 90))
        self.caixa_texto.setStyleSheet("font:bold;\n"
                                       "font-size:15px;\n"
                                       "border-style: outset;\n"
                                       "border-width: 2px;\n"
                                       "border-radius: 10px;\n"
                                       "border-color: purple;")
        self.caixa_texto.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignTop)
        self.caixa_texto.setObjectName("caixa_texto")
        self.caixa_texto.returnPressed.connect(self.botaoenviar_click)

        self.maid = QtWidgets.QLabel(self.centralwidget)
        self.maid.setGeometry(QtCore.QRect(445, 70, 345, 400))
        self.maid.setMinimumSize(QtCore.QSize(345, 400))
        self.maid.setMaximumSize(QtCore.QSize(345, 400))
        self.maid.setStyleSheet("border-style: outset;\n"
                                "border-width: 3px;\n"
                                "border-color: green;\n")
        self.maid.setText("")
        self.maid.setPixmap(QtGui.QPixmap("index.png"))
        self.maid.setObjectName("maid")
        mainwindow.setCentralWidget(self.centralwidget)

        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(445, 10, 345, 56))
        self.label1.setStyleSheet("font: bold 20px \"MS Shell Dlg 2\";\n"
                                  "background-color: rgb(252, 254, 235);\n"
                                  "border-style: outset;\n"
                                  "border-width: 3px;\n"
                                  "border-radius: 5px;\n"
                                  "border-color: green;")
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")

        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 431, 461))
        self.textBrowser.setStyleSheet("background-color: rgb(252, 254, 235);\n"
                                       "border-style: outset;\n"
                                       "border-width: 3px;\n"
                                       "border-radius: 10px;\n"
                                       "border-color: green")
        self.textBrowser.setObjectName("textBrowser")

        self.botao2 = QtWidgets.QToolButton(self.centralwidget)
        self.botao2.setGeometry(QtCore.QRect(230, 490, 200, 40))
        self.botao2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao2.setStyleSheet("font: bold 15px \"MS Shell Dlg 2\";\n"
                                  "background-color: rgb(252, 254, 235);\n"
                                  "border-style: outset;\n"
                                  "border-width: 2px;\n"
                                  "border-radius: 10px;\n"
                                  "border-color: green;")
        self.botao2.setObjectName("botao2")
        self.botao2.clicked.connect(self.limparregistro)

        self.botaoitens = QtWidgets.QToolButton(self.centralwidget)
        self.botaoitens.setGeometry(QtCore.QRect(230, 540, 200, 40))
        self.botaoitens.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaoitens.setStyleSheet("font: bold 15px \"MS Shell Dlg 2\";\n"
                                      "background-color: rgb(252, 254, 235);\n"
                                      "border-style: outset;\n"
                                      "border-width: 2px;\n"
                                      "border-radius: 10px;\n"
                                      "border-color: green;")
        self.botaoitens.setObjectName("botaoitens")
        self.botaoitens.clicked.connect(self.removeItems)

        self.botao1 = QtWidgets.QToolButton(self.centralwidget)
        self.botao1.setGeometry(QtCore.QRect(20, 490, 200, 40))

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botao1.sizePolicy().hasHeightForWidth())

        self.botao1.setSizePolicy(sizePolicy)
        self.botao1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao1.setFocusPolicy(QtCore.Qt.TabFocus)
        self.botao1.setStyleSheet("font: bold 15px \"MS Shell Dlg 2\";\n"
                                  "background-color: rgb(252, 254, 235);\n"
                                  "border-style: outset;\n"
                                  "border-width: 2px;\n"
                                  "border-radius: 10px;\n"
                                  "border-color: green;")
        self.botao1.setObjectName("botao1")
        self.botao1.clicked.connect(mostraconfigs)

        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 200, 411, 261))
        self.listWidget.setStyleSheet("border-style: outset;\n"
                                      "alternate-background-color: rgb(247, 255, 255);\n"
                                      "background-color: rgb(225, 248, 253);\n"
                                      "border-width: 3px;\n"
                                      "border-radius: 10px;\n"
                                      "border-color: green")
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)

        menu = QMenu()

        openAction = menu.addAction("Abrir")
        openAction.triggered.connect(mostraprincipal)
        settingAction = menu.addAction("Opções")
        settingAction.triggered.connect(mostraconfigs)

        self.tray = QSystemTrayIcon()
        self.tray.setIcon(icon)
        self.tray.setContextMenu(menu)
        self.tray.show()
        self.tray.setToolTip("Maid-sama")
        self.tray.showMessage("Atenção!", "Maid-chan iniciando a todo vapor!!")
        self.tray.activated.connect(mostraprincipal)

        self.botaoitens.raise_()
        self.maid.raise_()
        self.label1.raise_()
        self.botaosair.raise_()
        self.caixa_texto.raise_()
        self.botao2.raise_()
        self.botao1.raise_()
        self.textBrowser.raise_()
        self.listWidget.raise_()

        def registropadrao():
            self.listWidget.addItem('Mestre este é o Registro!')
            self.listWidget.addItem('Por aqui você pode ver o que foi enviado anteriormente!')
            self.listWidget.addItem('Para excluir algum item basta seleciona-lo e apertar Excluir Selecionados!')
            self.listWidget.addItem('O botão "Limpar Tela" exclui todas as mensagens no Registro!')
            self.listWidget.addItem('\n ~ Maid chan')

        registropadrao()

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "Maid chan"))
        self.botaosair.setText(_translate("mainwindow", "Ocultar"))
        self.label1.setText(_translate("mainwindow", " Maid-chan"))
        self.textBrowser.setHtml(_translate("mainwindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Maid-chan 0.2</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Todos os direitos reservados</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Sugestões: sr.thales500@gmail.com</span></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">MEUS PRINCIPAIS COMANDOS: </span></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Abrir ou Executar: ( Executo o app digitado, lembre-se de usar os nomes padrões!)</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Abrir Site ou Site: ( Abro o site digitado usando o seu navegador padrão!)</p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Tempo: ( Apresento diversas informações sobre o tempo da cidade requisitada!)</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Pesquisar ou Pesquise: ( Realizo qualquer pesquisa digitada usando o google!)</span></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
                                            "<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">-Maid-chan   </span></p></body></html>"))
        self.botao2.setText(_translate("mainwindow", "Limpar Tela"))
        self.botao1.setText(_translate("mainwindow", "Opções"))
        self.botaoitens.setText(_translate("mainwindow", "Excluir Selecionados"))

    def botaoenviar_click(self):
        enviado = self.caixa_texto.text()
        enviado = enviado.strip()

        if enviado == "":
            self.caixa_texto.setText("")
            winsound.PlaySound('SystemExclamation', winsound.SND_ALIAS | winsound.SND_ASYNC)
            QMessageBox.about(MainWindow, "Alguma coisa deu errada!",
                              "Não consegui encontrar nenhum texto para enviar!")

        if enviado != "":
            self.listWidget.addItem(enviado)
            self.caixa_texto.clear()
            enviado = enviado.lower()

            if enviado[0:9] == "executar:":
                try:
                    enviado = enviado.replace("executar:", "")
                    enviado = enviado.strip()
                    os.startfile(enviado)
                    self.caixa_texto.clear()
                except OSError as err:
                    winsound.PlaySound('SystemExclamation', winsound.SND_ALIAS | winsound.SND_ASYNC)
                    QMessageBox.about(MainWindow, "Alguma coisa deu errada!", "OS error: {0}".format(err))
                    self.caixa_texto.clear()

            if enviado[0:6] == "abrir:":
                try:
                    enviado = enviado.replace("abrir:", "")
                    enviado = enviado.strip()
                    os.startfile(enviado)
                    self.caixa_texto.clear()
                except OSError as err:
                    winsound.PlaySound('SystemExclamation', winsound.SND_ALIAS | winsound.SND_ASYNC)
                    QMessageBox.about(MainWindow, "Alguma coisa deu errada!", "OS error: {0}".format(err))
                    self.caixa_texto.clear()

            if enviado[0:11] == "abrir site:":
                enviado = enviado.replace("abrir site:", "")
                enviado = enviado.strip()

                if "." not in enviado:
                    os.startfile("www." + enviado + ".com")
                    self.caixa_texto.clear()
                else:
                    os.startfile("http:" + enviado)
                    self.caixa_texto.clear()

            if enviado[0:5] == "site:":
                enviado = enviado.replace("site:", "")
                enviado = enviado.strip()

                if "." not in enviado:
                    os.startfile("www." + enviado + ".com")
                    self.caixa_texto.clear()
                else:
                    os.startfile("http:" + enviado)
                    self.caixa_texto.clear()

            if enviado[0:9] == "pesquise:":
                try:
                    enviado = enviado.replace("pesquise:", "")
                    enviado = enviado.strip()

                    enviado = enviado.replace(" ", "+")
                    os.startfile("www.google.com/search?&q=" + enviado + "&ie=UTF-8&oe=UTF-8")
                    self.caixa_texto.clear()

                except OSError as err:
                    winsound.PlaySound('SystemExclamation', winsound.SND_ALIAS | winsound.SND_ASYNC)
                    QMessageBox.about(MainWindow, "Alguma coisa deu errada!", "OS error: {0}".format(err))
                    self.caixa_texto.clear()

            if enviado[0:10] == "pesquisar:":
                try:
                    enviado = enviado.replace("pesquisar:", "")
                    enviado = enviado.strip()

                    enviado = enviado.replace(" ", "+")
                    os.startfile("www.google.com/search?&q=" + enviado + "&ie=UTF-8&oe=UTF-8")
                    self.caixa_texto.clear()

                except OSError as err:
                    winsound.PlaySound('SystemExclamation', winsound.SND_ALIAS | winsound.SND_ASYNC)
                    QMessageBox.about(MainWindow, "Alguma coisa deu errada!", "OS error: {0}".format(err))
                    self.caixa_texto.clear()

            if enviado[0:6] == "tempo:":
                try:
                    enviado = enviado.replace("tempo:", "")
                    enviado = enviado.strip()
                    cidade = enviado
                    requisicao = requests.get(
                        "http://api.openweathermap.org/data/2.5/weather?q=" + cidade + "&lang=pt_br&appid=1be8401c6f45bbe58134a735f9eece28")

                    tempo = json.loads(requisicao.text)

                    ventospeed = tempo['wind']['speed']
                    tempmax = tempo['main']['temp_max'] - 273.15
                    tempmin = tempo['main']['temp_min'] - 273.15
                    tempgraus = tempo['main']['temp'] - 273.15

                    localizacaowindow.show()
                    localizacaowindow.Labelnome.setText(str(tempo['name'] + ', ' + tempo['sys']['country']))
                    localizacaowindow.Labelclima.setText(str(tempo['weather'][0]['description']))
                    localizacaowindow.Labelmax.setText(str('{0:.1f}').format(tempmax) + ' °')
                    localizacaowindow.Labelmin.setText(str('{0:.1f}').format(tempmin) + ' °')
                    localizacaowindow.Labelumidade.setText(str(tempo['main']['humidity']) + ' %')
                    localizacaowindow.Labeltemp.setText(str('{0:.1f}').format(tempgraus) + ' °')
                    localizacaowindow.Labelventospeed.setText(str(ventospeed) + ' m/s')

                except KeyError:
                    winsound.PlaySound('SystemExclamation', winsound.SND_ALIAS | winsound.SND_ASYNC)
                    QMessageBox.about(MainWindow, "Alguma coisa deu errada!",
                                      "Mestre, Não consegui identificar a cidade!\n\n"
                                      "Por Favor confira se o nome foi inserido corretamente!")

    def limparregistro(self):
        self.listWidget.clear()
        winsound.PlaySound('SystemExclamation', winsound.SND_ALIAS | winsound.SND_ASYNC)
        QMessageBox.about(MainWindow, "Grande sucesso!", "Registro limpo com sucesso!")

    def removeItems(self):
        for item in self.listWidget.selectedItems():
            self.listWidget.takeItem(self.listWidget.row(item))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)

    configwindow = uic.loadUi("settingsmaid.ui")
    localizacaowindow = uic.loadUi("localizacao.ui")

    configwindow.botaovoltar.clicked.connect(mostraprincipal)
    configwindow.botaovoltar2.clicked.connect(mostraprincipal)
    configwindow.botaocompartilhar.clicked.connect(copialink)
    configwindow.botaosugerir.clicked.connect(sugeremudanca)
    configwindow.botaoiniciar.clicked.connect(abreaoiniciar)
    configwindow.botaoprogramas.clicked.connect(adicionarprogramas)

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
